data:
  root_dir: '/home/yjunj/data/barcode'
  batch_size: 4
  input_size: [ 400, 640 ]
  num_workers: 0
  task: 'geo_qroi'
  quality_path:
  img_aug: true
  geo_aug: false

model:
  in_channels: 1
  out_channels: 9
  object_classes: 3
  geometry_channels: 6
  enable_qroi: true
  base_channels: 12
  depth: 1
  head_channels: 24
  interpolation: 'nearest'
  gamma: 2.0
  alpha: 0.5
  init_lr: 5e-4
  lambda_geo: 1.0
  lambda_qroi: 1.0
  qroi_pool_size: 7
  qroi_eps: 0.2

trainer:
  accelerator: 'auto'
  strategy: 'auto'
  devices: 1
  precision: '32-true'
  max_epochs: 2
  sync_batchnorm: False
  check_val_every_n_epoch: 1
  limit_train_batches: 20
  limit_val_batches: 5
  num_sanity_val_steps: 0
