data:
  root_dir: '/home/yjunj/data/barcode'
  batch_size: 12
  input_size: [ 400, 640 ]
  num_workers: 4
  task: 'geo_qroi'
  quality_path: '/home/yjunj/data/barcode/qroi_labels/roi_quality.v2.jsonl'
  img_aug: false
  geo_aug: false
  viz:
    heatmap_max_images: 16
    qroi_max_images: 16

model:
  in_channels: 1
  out_channels: 9
  object_classes: 3
  geometry_channels: 6
  enable_qroi: true
  base_channels: 24
  depth: 2
  head_channels: 48
  interpolation: 'nearest'
  gamma: 2.0
  alpha: 0.1
  init_lr: 5.0e-5
  lambda_geo: 0.5
  lambda_qroi: 1.0
  qroi_pool_size: 7
  qroi_eps: 0.2

wandb:
  enabled: true
  project: 'heatmap-model'

trainer:
  accelerator: 'gpu'
  strategy: 'ddp'
  devices: 4
  precision: '16-mixed'
  max_epochs: 150
  sync_batchnorm: True
  check_val_every_n_epoch: 2
  save_top_k: 40
  early_stopping:
    monitor: val_loss
    patience: 15
    min_delta: 1.0e-4
