data:
  root_dir: '/home/pover/Datasets/barcode'
  batch_size: 8
  input_size: [ 640, 1024 ]
  task: 'geo_qroi'
  quality_path:
  img_aug: true
  geo_aug: false

model:
  in_channels: 1
  out_channels: 9
  object_classes: 3
  geometry_channels: 6
  enable_qroi: true
  base_channels: 32
  depth: 2
  head_channels: 64
  interpolation: 'nearest'
  gamma: 2.0
  alpha: 0.5
  init_lr: 5e-4
  lambda_geo: 1.0
  lambda_qroi: 1.0
  qroi_pool_size: 7
  qroi_eps: 0.2

trainer:
  accelerator: 'auto'
  strategy: 'auto'
  devices: 'auto'
  precision: '32-true'
  max_epochs: 500
  sync_batchnorm: True
  check_val_every_n_epoch: 2
